version: "3.8"

services:
  mysqldb:
    image: mariadb:10
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./src/main/resources/sqlstuff/localsqltouse/import_ready_db_100percent.sql:/docker-entrypoint-initdb.d/0_init.sql
  app:
    depends_on:
      mysqldb:
        condition: service_started
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mariadb://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MariaDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "none"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://mysqldb:$MYSQLDB_DOCKER_PORT" ]
#      interval: 60s
#      timeout: 10s
#      retries: 50
volumes:
  db: