version: "3.8"

services:
  mysqldb:
    image: mariadb:10
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    healthcheck:
      test: [ "CMD", "/usr/bin/mysql", "--user=$MYSQLDB_USER",  "--password=$MYSQLDB_ROOT_PASSWORD", "--database=$MYSQLDB_DATABASE", "--execute", "SELECT * FROM todayssong;" ]
      interval: 20s
      timeout: 5s
      retries: 30
    volumes:
      - db:/var/lib/mysql
      - ./src/main/resources/sqlstuff/localsqltouse/import_ready_db_100percent.sql:/docker-entrypoint-initdb.d/0_init.sql
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mariadb://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MariaDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "none"
      }'
    volumes:
      - myapp:/app
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db:
  myapp: